<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
	public function findStudentsByCareer($careerId) {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('s.id, s.name, s.firstLastName, s.secondLastName, s.age, s.semester')
            ->from('AppBundle:Student', 's')
            ->where('s.career = :careerId')
            ->setParameter('careerId', $careerId);

        return $dql->getQuery()->getResult();
    }
}
