easy_admin: 
    site_name: Demo
    formats:
      date: 'd/m/Y'
    design:
      color_scheme: 'dark'
      form_theme: 'horizontal'
    list:
        max_results: 10
        actions:
            - { name: 'show', label: '', icon: 'search'}
            - { name: 'edit', label: '', icon: 'pencil' }
            - { name: '-delete', label: '', icon: '' }
            - { name: 'search', label: 'Búsqueda' }
    show:
        actions:
            - { name: 'edit', label: 'Actualizar' }
            - { name: 'list', label: 'Regresar al menu' }
    edit:
        actions:
            - { name: 'list', label: 'Regresar al menú' }
    new:
        actions:
            - { name: 'list', label: 'Regresar al menú' }
    entities:
        Student:
            label: 'Alumnos'
            class: AppBundle\Entity\Student
            list:
                title: "Alumnos inscritos"
                actions: [{ name: 'new', label: 'Agregar Alumno' }]
        Career:
            label: 'Carreras'
            class: AppBundle\Entity\Career
            list:
                title: "Oferta Académica"
                actions: [{ name: 'new', label: 'Agregar Carrera' }]
